# Assessment test 

## Exercise 1: 

What is a correct syntax to output "Hello World" in Python?

1. print("Hello World")
2. echo("Hello World")
3. p("Hello World")
4. printf("Hello World")

**You answer here**

In [1]:
print("Hello world")

Hello world


## Exercise 2:

Which one is NOT a legal variable name?

1. Myvar
2. _myvar
3. my-var
4. my_var

**Your answer here**

In [ ]:
_myvar

## Exercise 3: range()

Use range() to print all the even numbers from 0 to 10.

In [1]:
for i in range(0,11,2):
    print(i)

0
2
4
6
8
10


## Exercise 4: list


```python
>>> arr = ["Car", "Fruit", 1]
```

1. Add element at the top of the list `arr`
2. Add element at the end of the list `arr`
3. remove element "Car" from the list

In [11]:
arr=["Car", "Fruit", 1]
arr.insert(0,"bus")
print(arr)
arr.append(2)
print(arr)
arr.pop(1)
print(arr)

['bus', 'Car', 'Fruit', 1]
['bus', 'Car', 'Fruit', 1, 2]
['bus', 'Fruit', 1, 2]


## Exercise 5: slicing

```python
>>> arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```
1. Print the first 10 elements
2. Print the last 10 elements 
3. Print the elements between indices 3 and 7
4. Print the elements at odd positions

In [18]:
arr=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
a=slice(10)
print(arr[a])
b=slice(-10,20)
print(arr[b])
c=slice(4,7)
print(arr[c])
for i in range(1,20,2):
   if(i%2==1):
        print(i)

    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[4, 5, 6]
1
3
5
7
9
11
13
15
17
19


## Exercise 6: List comprehension

Use List comprehension to create a list of all numbers between 1 and 50 that are divisible by 3.

In [9]:
list=[i for i in range(1,51) if(i%3==0)]
print(list)


[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]


## Exercise 7: string

Go through the string below and if the length of a word is even print "even!"
```python
>>> st = 'Print every word in this sentence that has an even number of letters'
```

In [14]:
st='Print every word in this sentence that has an even number of letters'
x=st.split()
for i in x:
    if len(i)%2==0:
        print(i)

word
in
this
sentence
that
an
even
number
of


## Exercise 8: string

Write a program that prints the integers from 1 to 100. But for multiples of three print "Fizz" instead of the number, and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz".

In [12]:
x=[i for i in range(1,101)]
for i in x:
    if i%3==0 and i%5==0:
        print("FizzBuzz")
    if i%3==0:
        print("Fizz")
    elif(i%5==0):
        print("Buzz")

Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Fizz
Buzz
Fizz
Fizz
Buzz
Fizz
FizzBuzz
Fizz
Fizz
Buzz
Fizz
Fizz
Buzz


## Exercise 9: conditions

1. Compute the odd number squares sum of `arr`

```python
>>> arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```

2. Compute the solution of $ax^2 + bx + c = 0$
    - a, b, and c are given by the user

In [7]:
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
x=0
for i in arr:
    if i%2==1:
        x+=i**2
print(x)

a=int(input("Enter a!: "))
b=int(input("Enter b!: "))
c=int(input("Enter c!: "))
d=b**2-4*a*c
if(d==0):
    print("l'equatin ax^2 + bx + c = 0 admet une solution qui est: -b/2a=",-b/(2*a))
elif(d>0):
    print("l'equatin ax^2 + bx + c = 0 admet deux solutions qui sont:",(-b+sqrt(d))/2*a,"and",(-b-sqrt(d))/2*a)
else:
    print("l'equatin ax^2 + bx + c = 0 n'admet pas de solution")


1330
Enter a!: 1
Enter b!: 4
Enter c!: 4
l'equatin ax^2 + bx + c = 0 admet une solution qui est: -b/2a= -2.0


## Exercise 10: Numpy

1. Define 2 matrices using numpy

![matrix](../data/matrix.png)

2. Compute the multiplication of the 2 matrices

3. Print the result

In [1]:
import numpy as np

matrix1 = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])

matrix2 = np.array([[1, 2, 3],
                    [4, 5, 6]])

result = np.dot(matrix1, matrix2)

print(result)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


## Exercise 11: functions

1. Write function that compute the max of 2 given numbers
2. Call the function with 2 numbers of your choice

In [6]:
def max_of_two(num1, num2):
    return max(num1, num2)
result = max_of_two(10, 20)
print(result)


20


## Exercise 12: Matplotlib
 
1. Write a Python program that will create the plot bellow
![plot](../data/matplotlib.png)

In [14]:
# Your code here

## Exercise 13: pandas

1. Use pandas library to read the csv file 'data.csv' (located at data repository)
2. Print the first 10 rows for the file
3. Print the values of 'diagnosis' column

In [14]:
# Your code here